name: SonarQube analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: SonarQube scan
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests (generate coverage)
        run: npm run test -- --coverage; exit 0

      - name: Build project
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Replace the action step with Windows CLI version
      - name: Run SonarQube Scanner
          run: |
          "D:\IDE Tool\sonar-scanner\bin\sonar-scanner.bat" ^
            -Dsonar.projectKey=myorg_my-astro-site ^
            -Dsonar.sources=src ^
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/.astro/**,**/*.md ^
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info ^
            -Dsonar.host.url=%SONAR_HOST_URL% ^
            -Dsonar.login=%SONAR_TOKEN%
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
